server:
  port: 8080

spring:
  application:
    name: loan-management

  # ========================
  # DATABASE CONFIGURATION
  # ========================
  datasource:
    url: jdbc:postgresql://localhost:5432/loan_management_db
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # ========================
  # JPA CONFIGURATION
  # ========================
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # ========================
  # FLYWAY CONFIGURATION
  # ========================
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  # ========================
  # OAUTH2 CONFIGURATION
  # ========================
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#          client-id: ${GOOGLE_CLIENT_ID}
#          client-secret: ${GOOGLE_CLIENT_SECRET}
#          scope:
#              - email
#              - profile
#          github:
#            client-id: ${GITHUB_CLIENT_ID}
#            client-secret: ${GITHUB_CLIENT_SECRET}
#            scope:
#              - user:email
#              - read:user
  # ========================
  # MAIL CONFIGURATION
  # ========================
#  mail:
#        host: smtp.gmail.com
#        port: 587
#        username: ${MAIL_USERNAME}
#        password: ${MAIL_PASSWORD}
#        properties:
#          mail:
#            SMTP:
#              auth: true
#              STARTTLS:
#                enable: true

# ========================
# JWT CONFIGURATION
# ========================
jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: ${JWT_ACCESS_EXPIRY:900000}
  refresh-token-expiry: ${JWT_REFRESH_EXPIRY:604800000}

# ========================
# LOGGING CONFIGURATION
# ========================
logging:
  level:
    com.loanmanagement: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
